# Nombre del microservicio
spring.application.name=msvc-cursos

# Puerto donde corre este microservicio
server.port=8002

# Conexión PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/msvc_cursos
#spring.jpa.properties.hibernate.default_schema=msvc_cursos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Dialecto de Hibernate
spring.jpa.generate-ddl=true

# Crear tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logs SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
