# Nombre del microservicio
spring.application.name=msvc-usuarios

# Puerto donde corre este microservicio
server.port=8001

# Conexión MySQL (Laragon)
spring.datasource.url=jdbc:mysql://localhost:3306/msvc_users?serverTimezone=America/Mexico_City
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Crear tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Logs SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
